<table>
<tr><td><img style="height: 150px;" src="images/geo_hydro1.jpg"></td>
<td bgcolor="#FFFFFF">
    <p style="font-size: xx-large; font-weight: 900; line-height: 100%">AG Dynamics of the Earth</p>
    <p style="font-size: large; color: rgba(0,0,0,0.5);">Jupyter notebooks</p>
    <p style="font-size: large; color: rgba(0,0,0,0.5);">Georg Kaufmann</p>
    </td>
</tr>
</table>

# Numerical methods: 7. Linear systems
## Library version

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import numerics.lingl
import numerics.change_fonts;numerics.change_fonts.change_fontsize()

## Gauss elimination without pivoting

In [2]:
a=np.array([[2.,1.,-1.],[1.,3.,1.],[-1.,1.,4.]])
b=np.array([4.,3.,4.])

a2=np.copy(a); b2=np.copy(b)
print('A_ij: ',a,a.ndim,a.shape)
print('b_j:  ',b,b.ndim,b.shape)
a2=np.copy(a); b2=np.copy(b)
x=numerics.lingl.lin_gauss(a2,b2)
print('x_i:  ',x,x.ndim,x.shape)
print(np.allclose(np.dot(a, x), b))

# check against numpy solution
a2=np.copy(a); b2=np.copy(b)
x = np.linalg.solve(a2, b2)
print('x_i:  ',x,x.ndim,x.shape)
print(np.allclose(np.dot(a, x), b))

A_ij:  [[ 2.  1. -1.]
 [ 1.  3.  1.]
 [-1.  1.  4.]] 2 (3, 3)
b_j:   [4. 3. 4.] 1 (3,)
x_i:   [ 3.46153846 -0.84615385  2.07692308] 1 (3,)
True
x_i:   [ 3.46153846 -0.84615385  2.07692308] 1 (3,)
True


## LU decomposition

In [3]:
a=np.array([[2.,1.,-1.],[1.,3.,1.],[-1.,1.,4.]])
b=np.array([4.,3.,4.])

a2=np.copy(a); b2=np.copy(b)
print('A_ij: ',a,a.ndim,a.shape)
print('b_j:  ',b,b.ndim,b.shape)
a2=np.copy(a); b2=np.copy(b)
l,u = numerics.lingl.lin_lu_decompose(a2)
x   = numerics.lingl.lin_lu_solve(l,u,b2)
print('x_i:  ',x,x.ndim,x.shape)
print(np.allclose(np.dot(a, x), b))

# check against numpy solution
a2=np.copy(a); b2=np.copy(b)
x = np.linalg.solve(a2, b2)
print('x_i:  ',x,x.ndim,x.shape)
print(np.allclose(np.dot(a, x), b))

A_ij:  [[ 2.  1. -1.]
 [ 1.  3.  1.]
 [-1.  1.  4.]] 2 (3, 3)
b_j:   [4. 3. 4.] 1 (3,)
x_i:   [ 3.46153846 -0.84615385  2.07692308] 1 (3,)
True
x_i:   [ 3.46153846 -0.84615385  2.07692308] 1 (3,)
True


... done