<table>
<tr><td><img style="height: 150px;" src="images/geo_hydro1.jpg"></td>
<td bgcolor="#FFFFFF">
    <p style="font-size: xx-large; font-weight: 900; line-height: 100%">AG Dynamics of the Earth</p>
    <p style="font-size: large; color: rgba(0,0,0,0.5);">Jupyter notebooks</p>
    <p style="font-size: large; color: rgba(0,0,0,0.5);">Georg Kaufmann</p>
    </td>
</tr>
</table>

# Numerical methods: Tri-diagonal system
----
*Georg Kaufmann,
Geophysics Section,
Institute of Geological Sciences,
Freie Universität Berlin,
Germany*

In [1]:
import numpy as np
import numpy.linalg
import scipy.linalg

Define test matrix ${\bf A}$ for notebook:

In [2]:
a = np.array([[2.,3.,0.,0.], [6.,3.,9.,0.],[0.,2.,5.,2.],[0.,0.,4.,3.]])
print(a)

[[2. 3. 0. 0.]
 [6. 3. 9. 0.]
 [0. 2. 5. 2.]
 [0. 0. 4. 3.]]


In [3]:
a = np.array([2.,3.,5.,3.])
b = np.array([3.,9.,2.])
c = np.array([6.,2.,4.])
rhs = np.array([21,69,34,22])

## LU decomposition

Test LU decomposition with our routines and the in-buld `python` routines.

In [4]:
def lin_tridiag(a,b,c,rhs):
    '''
    !-----------------------------------------------------------------------
    ! subroutine solves the system of linear equations
    ! a(n,n)*x(n) = b(n)
    ! for a tri-diagonal band matrix a(n,n), stored as
    ! vectors a(n),b(n),c(n)
    ! Input:
    ! n       - number of equations
    ! a(n)    - coefficient vector
    ! b(n)    - coefficient vector
    ! c(n)    - coefficient vector
    ! rhs(n)  - rhs vector
    ! Output:
    ! x(n)    - solution vector
    ! (c) Georg Kaufmann
    !-----------------------------------------------------------------------
    '''
    n = rhs.shape[0]
    # use LU decomposition Ax=LUx=b => Ly=b and Ux=y
    l = np.zeros([n]); u =np.zeros([n])
    l[0] = a[0]
    u[0] = b[0]/a[0]
    for i in range(1,n): #i=1,n-1
        l[i-1] = a[i-1] - c[i-1]*u[i-2]
        u[i-1] = b[i-1] / l[i-1]
    l[n-1] = a[n-1] - c[n-1]*u[n-2]

    # solve decomposed system Ly=b with forward substitution
    y[0] = rhs[0]/l[0]
    for i in range(2,n+1): # i=2,n
        y[i-1] = (rhs[i-1]-c[i-1]*y[i-2])/l[i-1]
    
    # solve decomposed system Ux=y with backward substitution
    x[n-1] = y[n-1]
    for j in range(1,n): # j=1,n-1
        i    =  n-j
        x[i-1] =  x[i-1]-u[i-1]*y[i]
    return x

In [5]:
x = lin_tridiag(a,b,c,rhs)
print(x)
#print(np.allclose(a2 - l @ u, np.zeros((a.shape[0], a.shape[0]))))


/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:26: RuntimeWarning: divide by zero encountered in double_scalars


IndexError: index 3 is out of bounds for axis 0 with size 3

## Determinant
Test calculation of determinant of matrix ${\bf A}$ with our routines and the in-buld `python` routines.

In [ ]:
def lin_det(a):
    l,u = lin_lu_decompose(a)
    det = 1.
    for i in range(a.shape[0]):
        det = det * u[i,i]
    return det

In [ ]:
a2 = np.copy(a)
det = lin_det(a2)
print (det)

a2 = np.copy(a)
det = numpy.linalg.det(a2)
print (det)

## Inversion
Test calculation of inverse ${\bf A}^{-1}$ with our routines and the in-buld `python` routines.

In [ ]:
def lin_inverse(a):
    n = a.shape[0]
    ainv = np.zeros(n*n).reshape(n,n)
    for i in range(n):
        ainv[i,i] = 1.
    l,u = lin_lu_decompose(a)
    for i in range(n):
        ainv[:,i] = lin_lu_solve(l,u,ainv[:,i])
    return ainv

In [ ]:
a2 = np.copy(a)
ainv=lin_inverse(a2)
print (ainv)
print(np.allclose(np.dot(a2, ainv), np.eye(a.shape[0])))

a2 = np.copy(a)
ainv=numpy.linalg.inv(a2)
print (ainv)
print(np.allclose(np.dot(a2, ainv), np.eye(a.shape[0])))

... done