<table>
<tr><td><img style="height: 150px;" src="images/geo_hydro1.jpg"></td>
<td bgcolor="#FFFFFF">
    <p style="font-size: xx-large; font-weight: 900; line-height: 100%">AG Dynamics of the Earth</p>
    <p style="font-size: large; color: rgba(0,0,0,0.5);">Juypter notebooks</p>
    <p style="font-size: large; color: rgba(0,0,0,0.5);">Georg Kaufmann</p>
    </td>
</tr>
</table>

# Numerical methods: 7. Linear systems
## Working with scalars, vector, and matrices
----
*Georg Kaufmann,
Geophysics Section,
Institute of Geological Sciences,
Freie Universität Berlin,
Germany*

In this notebook, we refresh our knowledge on **matrix algebra** and implement vectors and matrices in python.

In [1]:
import numpy as np
import numpy.linalg

----
## Scalars

We first define two **scalars**, $\alpha$ as integer and $\beta$ as float:
$$
\begin{array}{rcl}
\alpha &=& 1 \\
\beta &=& 2.
\end{array}
$$
Examine in `python`:

In [2]:
alpha = 1
beta  = 2.
print ('scalar alpha')
print(alpha,type(alpha))
print ('scalar beta')
print(beta,type(beta))

scalar alpha
1 <class 'int'>
scalar beta
2.0 <class 'float'>


----
## Vectors

Next, we define two vectors.

A **row** vector:
$$
\vec{a} = (1,2,3)
$$
and a **column** vector:
$$
\vec{b} = \left(
\begin{array}{c}
1\\2\\3
\end{array}
\right)
$$
In general, there is no real difference between these two, ecept when you write them
as ($1 \times n$)-matrix (row vector) or ($n \times 1$)-matrix (column vector).

We express both vectors with `python`, and calculate the
**scalar product**
$$
\vec{a} \cdot \vec{b}
$$

In [8]:
# row vector
a=np.array([1,2,3])
print('row vector a')
print(a,a.ndim,a.shape)
# column vector (as m x 1 matrix)
b=np.array([1,2,3]).reshape(3,1)
print('column vector b')
print(b,b.ndim,b.shape)
# scalar product
print('scalar product a*b')
print(np.dot(a,b))

# careful!!
#print(a+b)

row vector a
[1 2 3] 1 (3,)
column vector b
[[1]
 [2]
 [3]] 2 (3, 1)
scalar product a*b
[14]


----
## Matrices

Now, we define a general ($n \times m$)-matrix $A_{n,m}$ with $n=3$ and $m=3$:
$$
\mathbb{A} = \left[
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
\right]
$$

The **unity matrix** $\mathbb{I}$ is defined as being **one** on the main diagonal,
and **zero** elsewhere:
$$
\mathbb{I} = \left[
\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}
\right]
$$

We then perform the **matrix-matrix multiplication**:
$$
\mathbb{A} \cdot \mathbb{I}
$$
and a **matrix-vector multiplication**:
$$
\mathbb{I} \cdot \vec{a}
$$
In `python` this read:

In [9]:
#A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print('matrix A')
print(A,A.ndim,A.shape)
# unity matrix
I=np.eye(3)
print('Unity matrix I')
print(I,I.ndim,I.shape)
# matrix x matrix
B=np.matmul(A,I)
print('matrix-matrix product B= A*I')
print(B,B.ndim,B.shape)
# matrix x vector
C=np.matmul(I,a)
print('matrix-vector product C=I*a')
print(C)

matrix A
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 (3, 3)
Unity matrix I
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 (3, 3)
matrix-matrix product B= A*I
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 2 (3, 3)
matrix-vector product C=I*a
[1. 2. 3.]


A **transposed** matrix $\mathbb{A}^{T}$ can be obtained by swapping rows and columns:
$$
\mathbb{A}^T = a^T_{ij} = a_{ji}
$$

As **inverse** matrix $\mathbb{D}^{-1}$ we define a matrix, for which
$$
\mathbb{D} \cdot \mathbb{D}^{-1} = \mathbb{I}
$$
holds.
Check with `python`.

In [10]:
At=A.transpose()
print('transposed matrix A^T')
print(At)

D=np.array([[1., 2.], [3., 4.]])
Di=numpy.linalg.inv(D)
print('matrix D')
print(D)
print('inverse matrix D^{-1}')
print(Di)
print('D D^{-1}')
print(np.dot(D,Di))

transposed matrix A^T
[[1 4 7]
 [2 5 8]
 [3 6 9]]
matrix D
[[1. 2.]
 [3. 4.]]
inverse matrix D^{-1}
[[-2.   1. ]
 [ 1.5 -0.5]]
D D^{-1}
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


A note on matrix multiplications in `python`.

In [11]:
A = np.ones((2,2))
B = 2*A
print(A,A.shape)
print(B,B.shape)

print('np.matmul(A,B): matrix multiplication')
print(np.matmul(A,B))
print('np.multiply(A,B): element-wise multiplication')
print(np.multiply(A,B))
print('A*B: as np.multiply')
print(A*B)
print('np.dot(A,B): as np.matmul (but check man page)')
print(np.dot(A,B))
print('A@B: as np.matmul')
print(A @ B)

[[1. 1.]
 [1. 1.]] (2, 2)
[[2. 2.]
 [2. 2.]] (2, 2)
np.matmul(A,B): matrix multiplication
[[4. 4.]
 [4. 4.]]
np.multiply(A,B): element-wise multiplication
[[2. 2.]
 [2. 2.]]
A*B: as np.multiply
[[2. 2.]
 [2. 2.]]
np.dot(A,B): as np.matmul (but check man page)
[[4. 4.]
 [4. 4.]]
A@B: as np.matmul
[[4. 4.]
 [4. 4.]]


[next>](Numerics_lab07_gauss.ipynb)